name: Terraform CI (plan-only)

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    # Run all shell steps inside the module folder
    defaults:
      run:
        working-directory: infra/m1-network

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Skip when the module has no *.tf yet
      - name: No Terraform files yet – skipping checks
        if: ${{ hashFiles('infra/m1-network/**/*.tf') == '' }}
        run: echo "No Terraform files in infra/m1-network; skipping."

      - name: Setup Terraform
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform init (no backend)
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform init -backend=false

      - name: Terraform fmt
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform fmt -check

      - name: Terraform validate
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform validate

      - name: Setup TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: tflint --recursive

      - name: Run Checkov
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/m1-network
          quiet: true

      - name: Terraform plan (offline)
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform plan -refresh=false -input=false -lock=false -no-color -out=tfplan