name: Terraform CI (plan-only)

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    # run all commands inside the module folder
    defaults:
      run:
        shell: bash
        working-directory: infra/m1-network

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # simple debug so we see where we are
      - name: Debug - show files
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          pwd
          ls -la

      # if the module has no .tf yet, skip tools
      - name: No Terraform files yet – skipping
        if: ${{ hashFiles('infra/m1-network/**/*.tf') == '' }}
        run: echo "No .tf files under infra/m1-network; skipping."

      - name: Setup Terraform
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform init (no backend)
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform init -backend=false

      - name: Terraform fmt
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform fmt -check

      - name: Terraform validate
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform validate

      - name: Setup TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: tflint --recursive

      - name: Run Checkov
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true

    