name: Terraform CI (plan-only)

on:
  push:
    branches: [ "dev" ]
 
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/m1-network

    steps:
      - uses: actions/checkout@v4

      - name: Skip if no Terraform
        if: ${{ hashFiles('infra/m1-network/**/*.tf') == '' }}
        run: echo "No .tf files; skipping."

      - name: Setup Terraform
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt (check only)
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform fmt -check

      - name: Terraform validate
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: terraform validate

      - name: Setup TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        run: tflint --recursive

      - name: Run Checkov
        if: ${{ hashFiles('infra/m1-network/**/*.tf') != '' }}
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true